name: Build App

on:
  workflow_call:
    inputs:
      python_version:
        required: true
        type: string
        default: "3.9"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: ${{ inputs.python_version }}

    - name: Install dependencies
      run: |
        python3 -m pip install --upgrade pip
        pip3 install -r requirements.txt

    - name: Run migrations
      run: |
        python3 manage.py migrate        
