name: Build Docker Image

on:
  workflow_call:
    inputs:
      image_tag:
        required: true
        type: string
        default: "python-app"

env:
    AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ECS }}
    AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_KEY_ECS }}
    ECR_URI: ${{ vars.ECR_REPOSITORY_URI }}
    AWS_REGION: ${{ vars.AWS_REGION }}
    APP_VERSION: ${{ vars.APP_VERSION }}
    ECR_URL: "${{ vars.ECR_REPOSITORY_URI }}/${{ vars.ECR_NAME }}"

jobs:
  build-image:
    runs-on: ubuntu-latest 
    steps:
    - uses: actions/checkout@v4

    - name: Build Docker Image
      run: |
        echo "Building Docker Image ..."
        docker build -t ${{ inputs.image_tag }} .
        docker images
  
    - name: Log in to Amazon ECR
      run: |
        echo "Logging in to Amazon ECR in region $AWS_REGION with URI $ECR_URI"
        aws configure set aws_access_key_id "$AWS_ACCESS_KEY_ID"
        aws configure set aws_secret_access_key "$AWS_SECRET_ACCESS_KEY"
        aws configure set region "$AWS_REGION"
        aws ecr get-login-password --region us-east-1 | docker login --username AWS --password-stdin ${ECR_URI}

    - name: Push Image to ECR
      run: |
        SHORT_COMMIT_HASH=$(echo $GITHUB_SHA | cut -c1-8)
        IMAGE_NAME="${APP_VERSION}-${SHORT_COMMIT_HASH}"
        echo "Pushing ${IMAGE_NAME} to ECR..."
        docker tag ${{ inputs.image_tag }} $ECR_URL:$IMAGE_NAME
        docker push $ECR_URL:$IMAGE_NAME
