name: Build Docker Image

on:
  workflow_call:
    inputs:
      image_tag:
        required: true
        type: string
        default: "python-app:latest"

jobs:
  docker-build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4       

    - name: Build Docker Image
      run: |
        pwd
        docker build -t ${{ inputs.image_tag }} .

  upload-image:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Push Image to ECR
      run: |
        echo "Pushing ${{ inputs.image_tag }} to ECR..."
