name: Terrafrom

on:
  workflow_call:

jobs:
  terraform:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v4

    # - name: Configure AWS credentials
    #   uses: aws-actions/configure-aws-credentials@v3
    #   with:
    #     aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY }}
    #     aws-secret-access-key: ${{ secrets.AWS_SECRET_KEY }}
    #     aws-region: ${{ vars.AWS_REGION }}

    - name: Terraform Plan
      run: |
          cd terraform/project
          echo "terraform init"
          echo "terraform plan"

    - name: Terraform Apply
      run: |
          cd terraform/project
          ls
          echo "terraform apply -auto-approve -input=false"
          
